# Generated by Django 3.2.5 on 2021-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(choices=[('3DArt', '3Dart'), ('3DRendering', '3Drendering'), ('3DModeling', '3Dmodeling'), ('Painting', 'Painting')], default='3DArt', max_length=100),
        ),
    ]
