# Generated by Django 3.2.5 on 2021-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(choices=[('3D_Art', '3D Art'), ('3D_Rendering', '3D Rendering'), ('3D_Modeling', '3D Modeling'), ('Painting', 'Painting')], default='Select_a_Hobby', max_length=100),
        ),
    ]
