# Generated by Django 3.2.5 on 2021-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAnimations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_name', models.CharField(max_length=200)),
                ('animation_details', models.CharField(max_length=500)),
                ('animation_rating', models.FloatField(default=0)),
                ('animation_createdate', models.DateTimeField(verbose_name='date created at')),
            ],
        ),
        migrations.DeleteModel(
            name='MyAnimatins',
        ),
    ]
