# Generated by Django 3.2.5 on 2021-07-31 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0002_auto_20210731_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created at'),
        ),
    ]
