# Generated by Django 3.2.5 on 2021-07-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0003_alter_myanimations_animation_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myanimations',
            name='animation_createdate',
        ),
    ]
