# Generated by Django 3.2.5 on 2021-07-31 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0004_remove_myanimations_animation_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created at'),
        ),
    ]
