# Generated by Django 3.2.5 on 2021-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0005_myanimations_animation_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateTimeField(verbose_name='date created at'),
        ),
    ]
