# Generated by Django 3.2.5 on 2021-07-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0010_auto_20210731_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date created at'),
        ),
        migrations.AlterField(
            model_name='myanimations',
            name='animation_details',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
