# Generated by Django 3.2.5 on 2021-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0012_auto_20210731_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_details',
            field=models.TextField(blank=True, default='N/A', max_length=500, null=True),
        ),
    ]
