# Generated by Django 3.2.5 on 2021-07-31 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0013_alter_myanimations_animation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date created at'),
        ),
    ]
