# Generated by Django 3.2.5 on 2021-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0014_alter_myanimations_animation_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='animation_createdate',
            field=models.DateField(blank=True, null=True, verbose_name='date created at'),
        ),
    ]
