# Generated by Django 3.2.5 on 2021-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0015_alter_myanimations_animation_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimations',
            name='animation_image',
            field=models.ImageField(default='Images/None/Noimg.jpg', upload_to='Image/'),
        ),
    ]
