# Generated by Django 3.2.5 on 2021-08-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_hobbies'),
        ('myAnimations', '0017_alter_myanimations_animation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimations',
            name='animation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
