# Generated by Django 3.0.8 on 2021-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0018_myanimations_animation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanimations',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
