# Generated by Django 3.0.8 on 2021-08-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0019_auto_20210805_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myanimations',
            options={'ordering': ('id',)},
        ),
    ]
