# Generated by Django 3.0.8 on 2021-08-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0020_auto_20210805_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myanimations',
            options={},
        ),
    ]
