# Generated by Django 3.0.8 on 2021-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAnimations', '0021_auto_20210807_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimations',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
