# Generated by Django 3.0.8 on 2021-08-13 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAnimations', '0022_myanimations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myanimations',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myanimations',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
